### ISSUE TITLE
Bug: Item Duplication

### ISSUE THREAD

**Issue by Andyk10** [AnchyDev/RecycledItems#1]
### Current Behaviour

After recycling items and logging out of the game, when logging back in, the recycled items reappear in the inventory, and the items listed in the auction house are still there.

### Expected Behaviour

Items should be removed from the seller's inventory after being recycled.

### Steps to reproduce the problem

123

### AC rev. hash/commit

commit 60be029

### Operating system

windows 10 x64

**Comment by Andyk10** [comment]
@AnchyDev help!

**Comment by Andyk10** [comment]
Auction house recycled items will also disappear after the server restarts and will not be written to the database.

**Comment by AnchyDev** [comment]
> ### Current Behaviour
> 
> After recycling items and logging out of the game, when logging back in, the recycled items reappear in the inventory, and the items listed in the auction house are still there.

I see the issue and I will fix this on the weekend, as for the other problem can you open another issue to keep them separated? Thanks!

**Comment by Andyk10** [comment]
Alright, thank you for your work!
