### ISSUE TITLE
Feature: Add configuration option to allow bound items to be recycled.

### ISSUE THREAD

**Issue by Andyk10** [AnchyDev/RecycledItems#3]
### Current Behaviour

Manually deleted items can also be recycled. But bound items also be recycled after being deleted and become unbound.

### Expected Behaviour

Only unbound items should enter the auction house after being manually deleted.

### Steps to reproduce the problem

123

### AC rev. hash/commit

commit 60be029

### Operating system

windows 10 x64

**Comment by AnchyDev** [comment]
This was intentional but I might make it a configuration setting so you can decide if items that used to be unbound and have become bound can be recycled.

**Comment by Andyk10** [comment]
That's great!
