### ISSUE TITLE
Bug: After learning the blueprint, the blueprint is recycled.

### ISSUE THREAD

**Issue by Andyk10** [AnchyDev/RecycledItems#4]
### Current Behaviour

After learning the blueprint, the blueprint is recycled.

### Expected Behaviour

After learning the blueprint, the blueprint disappears and should not be recycled.
The blueprint is only recycled if it is recycled.

### Steps to reproduce the problem

123

### AC rev. hash/commit

commit 60be029

### Operating system

windows 10 x64

**Comment by Andyk10** [comment]
Opening the chest is the same.
@AnchyDev

**Comment by AnchyDev** [comment]
I might just remove the hook that recycles destroyed items which will avoid this problem and look at another approach in the future.

**Comment by AnchyDev** [comment]
I have fixed this in https://github.com/AnchyDev/RecycledItems/commit/3baea2403eaa371c6a532d61514b814b1d8f4052. I decided to just remove the feature of recycling when destroying items as it lead to a pretty crap experience. If you want to recycle items you need to either:
- Use the Recycler NPC
- Use the Remote Recycler Item
