### ISSUE TITLE
Bug: Rapid use of items 41178 causes a crash.

### ISSUE THREAD

**Issue by Andyk10** [AnchyDev/RecycledItems#5]
### Current Behaviour

Rapid use of items 41178 causes a crash. This is the crash log.
[gdb.txt](https://github.com/user-attachments/files/16171715/gdb.txt)

### Expected Behaviour

It does not cause a crash.

### Steps to reproduce the problem

123

### AC rev. hash/commit

commit 60be029

### Operating system

windows 10 x64

**Comment by Andyk10** [comment]
Please take a look when you have time, thank you.
@AnchyDev

**Comment by monteiroelias** [comment]
I was coming here to report something similar, the item Engineering: Weakness Spectralizers ID 42550 is also causing server crash. I notice a pattern that profession items cause this problem. Perhaps not allowing them is the solution that makes the most sense.

**Comment by AnchyDev** [comment]
> I was coming here to report something similar, the item Engineering: Weakness Spectralizers ID 42550 is also causing server crash. I notice a pattern that profession items cause this problem. Perhaps not allowing them is the solution that makes the most sense.

This should be unrelated, the script checks the item id before doing anything, otherwise it just proceeds as normal.

**Comment by AnchyDev** [comment]
This should be fixed by https://github.com/AnchyDev/RecycledItems/commit/d904fd60a2f0479c0f4576a05f21fef012ee16b9. Please re-open this issue if it is still happening.
